# Generated by Django 4.2.11 on 2024-04-21 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutdoorAirAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2024, 4, 21, 17, 1, 55, 780751))),
                ('place', models.CharField(max_length=200)),
                ('pm2_5', models.IntegerField()),
                ('temp', models.FloatField()),
                ('humidity', models.FloatField()),
            ],
        ),
    ]
