# Generated by Django 4.2.11 on 2024-04-21 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_outdoorairapi_time_indoorairapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outdoorairapi',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 21, 22, 37, 28, 311130)),
        ),
        migrations.AlterModelTable(
            name='outdoorairapi',
            table='OutdoorAir',
        ),
    ]
