# Generated by Django 5.0.4 on 2024-04-21 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dust', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='indoorair',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='outdoorair',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunSQL(
            "ALTER TABLE dust_outdoorair MODIFY COLUMN time DATETIME DEFAULT CURRENT_TIMESTAMP",
            reverse_sql="ALTER TABLE dust_outdoorair MODIFY COLUMN time DATETIME"
        ),
    ]
