# Generated by Django 5.0.4 on 2024-04-12 08:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dust', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 15, 35, 43, 947296)),
        ),
        migrations.AlterField(
            model_name='indoorair',
            name='outdoor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dust.outdoorair'),
        ),
        migrations.AlterField(
            model_name='indoorair',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 15, 35, 43, 946283)),
        ),
        migrations.AlterField(
            model_name='outdoorair',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 15, 35, 43, 869303)),
        ),
    ]
