# Generated by Django 5.0.4 on 2024-04-23 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dust', '0002_alter_health_time_alter_indoorair_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indoorair',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 23, 16, 42, 19, 61404, tzinfo=datetime.timezone.utc)),
        ),
    ]
