# Generated by Django 5.0.4 on 2024-04-12 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dust', '0002_alter_health_time_alter_indoorair_outdoor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indoorair',
            name='characteristic',
        ),
        migrations.AlterField(
            model_name='health',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 15, 39, 20, 812423)),
        ),
        migrations.AlterField(
            model_name='indoorair',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 15, 39, 20, 811424)),
        ),
        migrations.AlterField(
            model_name='outdoorair',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 15, 39, 20, 731323)),
        ),
    ]
