# Generated by Django 4.2.11 on 2024-04-16 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dust', '0003_remove_indoorair_characteristic_alter_health_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 16, 22, 47, 50, 719621)),
        ),
        migrations.AlterField(
            model_name='indoorair',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 16, 22, 47, 50, 719621)),
        ),
        migrations.AlterField(
            model_name='outdoorair',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 16, 22, 47, 50, 664363)),
        ),
    ]
