# Generated by Django 5.0.4 on 2024-04-23 16:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dust', '0003_alter_indoorair_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indoorair',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunSQL(
            "ALTER TABLE dust_health MODIFY COLUMN time DATETIME DEFAULT CURRENT_TIMESTAMP",
            reverse_sql="ALTER TABLE dust_health MODIFY COLUMN time DATETIME"
        ),
    ]
